### ISSUE TITLE
Wrong directory in openSUSE 13.2

### ISSUE THREAD

**Issue by ghost** [gustawho/fix-spotify-icon-plasma#1]
Using the metod https://github.com/aspiers/opensuse-spotify-installer
the directory change to
/opt/spotify/spotify-client/Data/resources.zip
I comprove it  changing "fix-spotify-icon.sh" at line 12 and 64
and works it.

**Comment by gustawho** [comment]
I use Arch Linux and Spotify was installed from AUR, which use /usr/share as base. I think I'll set a wizard to select the directory  or search for it and, when ready, choose what style use (dark or light).
